variables:
  LOCAL_IMAGE_NAME: '$CI_PROJECT_PATH-$CI_PIPELINE_ID'

test:
  stage: test
  before_script:
    - docker build -t $LOCAL_IMAGE_NAME .
  script:
    - docker run $LOCAL_IMAGE_NAME /bin/bash -c "cd /root/quicklisp/local-projects/trace-db && make check";
  after_script:
    - docker rmi -f $LOCAL_IMAGE_NAME
