variables:
  DOCKER_REGISTRY: "docker.grammatech.com:14850"
  LOCAL_IMAGE_NAME: '$CI_PROJECT_PATH-$CI_PIPELINE_ID'

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY

stages:
  - build-test-tag

build-test-tag:
  stage: build-test-tag
  script:
    - docker pull $DOCKER_REGISTRY/synthesis/clang:latest
    - docker build -f Dockerfile -t $LOCAL_IMAGE_NAME .

    # If on master branch, push test results to DataManager and push
    # up a new "latest" image, otherwise, run locally.
    - if [ "$CI_BUILD_REF_NAME" = "master" ];
      then
          docker run -e LOCAL_USER=root $LOCAL_IMAGE_NAME /bin/bash -c "cd /gt/trace-db && make check";
          docker tag $LOCAL_IMAGE_NAME $DOCKER_REGISTRY/$CI_PROJECT_PATH:latest;
          docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH:latest;
      else
          docker run -e LOCAL_USER=root $LOCAL_IMAGE_NAME /bin/bash -c "cd /gt/trace-db && make check";
      fi

    # Cleanup
    - docker rmi -f $LOCAL_IMAGE_NAME
