variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  image: $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/sel
  tags: ["kubernetes", "cluster"]
  before_script:
    - cp -r $(pwd)/ /root/quicklisp/local-projects/

check-format:
  stage: .pre
  script:
    - git lisp-format

build-manual:
  stage: test
  script:
    - GT=yes make doc

.test-template: &test
.test-template: &test
  stage: test
  script:
    - LISP=$LISP GT=yes make check

test-sbcl:
  variables:
    LISP: 'sbcl'
  <<: *test

test-ccl:
  variables:
    LISP: 'ccl'
  <<: *test
