@include include/sb-texinfo.texinfo

@menu
* Packages::                              API grouped by packages.
@end menu

@node Packages, , , API
@section Packages

The trace database is a collection of multiple Common Lisp @emph{packages}.  This
appendix holds each individual package's API in turn.

@menu
* core::                                  trace-db/core Trace database core.
* trace-db::                              trace-db/trace-db Trace database interface.
* sexp-trace-db::                         trace-db/sexp-trace-db S-expression trace database.
* binary-trace-db::                       trace-db/binary-trace-db Binary trace database.
* traceable::                             trace-db/traceable Traceable mixin.
* instrumentation-clang-instrument::      trace-db/instrumentation/clang-instrument Clang instrumentation.
@end menu

@node core, trace-db, Packages, Packages
@subsection core
@include trace-db-slash-core-sb-texinfo.texi

@node trace-db, sexp-trace-db, core, Packages
@subsection trace-db
@include trace-db-slash-trace-db-sb-texinfo.texi

@node sexp-trace-db, binary-trace-db, trace-db, Packages
@subsection sexp-trace-db
@include trace-db-slash-sexp-trace-db-sb-texinfo.texi

@node binary-trace-db, traceable, sexp-trace-db, Packages
@subsection binary-trace-db
@include trace-db-slash-binary-trace-db-sb-texinfo.texi

@node traceable, instrumentation-clang-instrument, binary-trace-db, Packages
@subsection traceable
@include trace-db-slash-traceable-sb-texinfo.texi

@node instrumentation-clang-instrument, Index, traceable, Packages
@subsection instrumentation-clang-instrument
@include trace-db-slash-instrumentation-slash-clang-instrument-sb-texinfo.texi
